quarantineradio/rooms/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class RoomForm(FlaskForm):
    title = StringField('Title', validators= [DataRequired()])
    description = TextAreaField('Description', validators= [DataRequired()])
    submit = SubmitField('Create')


class ChatForm(FlaskForm):
    description = TextAreaField('Description', validators= [DataRequired()])
    submit = SubmitField('Send')

quarantineradio/main/routes.py
from flask import render_template, request, Blueprint,url_for
from quarantineradio.models import Room
from flask_login import login_required, current_user


main =  Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/home')
@login_required
def home():
    page = request.args.get('page',1,type=int)
    rooms = Room.query.order_by(Room.date_posted.desc()).paginate(page=page, per_page=4)
    image_file = url_for('static', filename= 'img/'+ current_user.image_file)

    return render_template('home.html',title='Home', rooms=rooms, image_file=image_file)


# page 222

@main.route('/index')
def homee():
    page = request.args.get('page',1,type=int)
    posts = Room.query.order_by(Room.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('tuthome.html', posts=posts)

quarantineradio/rooms/routes.py
from time import localtime, strftime
from flask import (render_template, flash, redirect,
                    url_for, request, abort, Blueprint)
from flask_login import current_user, login_required
from quarantineradio import db
from quarantineradio.models import Room
from quarantineradio.rooms.forms import RoomForm,ChatForm
from quarantineradio import socketio
from flask_socketio import send, emit, join_room, leave_room




rooms =  Blueprint('rooms', __name__)
# room = Room.query.SelectorAll()

ROOMS = ["Lounge","News","Games","Code"]

@rooms.route('/room/new', methods=['POST','GET'])
@login_required
def post_new():
    form = RoomForm()
    if form.validate_on_submit():
        room = Room(title=form.title.data, description=form.description.data, room_creator=current_user)
        db.session.add(room)
        db.session.commit()
        flash('Post created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_room.html', title='New Room', form=form, legend='New Room')

@rooms.route('/room/<int:room_id>')
@login_required
def room(room_id):
    room = Room.query.get_or_404(room_id)
    # print("prining message now")
    form = ChatForm()

    return render_template('room.html', title= room.title, room=room, form=form, username= current_user.username )

@rooms.route('/about')
def about():
    return render_template('tutabout.html', title='About')



# event buckets for SocketIO

@socketio.on('message')
def message(data):

    print(f"\n\n{data}\n\n")
    send(data)

    send({'msg':data['msg'], 'username':data['username'],'device_id':data['device_id'],'track_uri':data['track_uri'],
    'time_stamp':strftime('%b-%d %I:%M%p', localtime())}, room=data['room'])
    emit('some-event' , 'this is a custom event message')

@socketio.on('join')
def join(data):

    join_room(data['room'])
    send({'msg':data['username'] + " has joined " + data['room_name'] + " room."}, room=data['room'])

@socketio.on('leave')
def leave(data):

    leave_room(data['room'])
    send({'msg':data['username'] + " has left " + data['room_name'] + " room."}, room=data['room'])




# @socketio.on('play')
# def join(data):
#
#     send({'msg':data['username'] + " is currently playing " + data['song_name'] + "."})

@rooms.route('/chat', methods= ['GET','POST'])
def chat():
    return render_template('chat.html', username= current_user.username, rooms=ROOMS)





@rooms.route('/room/<int:room_id>/update', methods=['POST','GET'])
@login_required
def update_room(room_id):
    room = Room.query.get_or_404(room_id)
    if room.room_creator != current_user:
        abort(403)
    form = RoomForm()
    if form.validate_on_submit():
        room.title = form.title.data
        room.description = form.description.data
        db.session.commit()
        flash('your room has been updated','success')
        return redirect(url_for('rooms.room', room_id=room.id))
    elif request.method == 'GET':
        form.title.data = room.title
        form.description.data = room.description
    return render_template('create_room.html', title='Update Room', form=form, legend='Update Room')

@rooms.route('/room/<int:room_id>/delete', methods=['POST'])
@login_required
def delete_room(room_id):
    room = Room.query.get_or_404(room_id)
    if room.room_creator != current_user:
        abort(403)
    db.session.delete(room)
    db.session.commit( )
    flash('your room has been delted','success')
    return redirect(url_for('main.home'))



# @socketio.on('message')
# def handle_message(data):
#     print('received message: ')

# @socketio.on('my event')
# def handl_event(data):
#     log.info('Recieved data: %s'%(data))
#     emit('my response', data)

quarantineradio/users/routes.py
from flask import (render_template, flash, redirect,
                    url_for, request, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from quarantineradio import db, bcrypt
from quarantineradio.models import User, Room
from quarantineradio.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                    RequestResetForm, ResetPasswordForm)
from quarantineradio.users.utils import save_picture, send_reset_email


users =  Blueprint('users', __name__)

# register form
@users.route('/signup', methods=['POST','GET'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has now been created. You can now log in','success')
        return redirect(url_for('users.signin'))
    return render_template('signup.html', title='Signup', form=form)


# login form
@users.route('/signin', methods=['GET','POST'])
def signin():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))

        else:
            flash('Login unsuccesful, please check email or password ', 'danger')
    return render_template('signin.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account',methods=['POST','GET'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            # picture_file = save_picture(form.picture.data)
            # current_user.image_file= picture_file
            current_user.image_file=form.picture.data

        current_user.username= form.username.data
        current_user.email= form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename= 'img/'+ current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_rooms(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Room.query.filter_by(room_creator=user)\
    .order_by(Room.date_posted.desc())\
    .paginate(page=page, per_page=4)
    return render_template('user_rooms.html', posts=posts,user=user)



@users.route('/reset_password', methods=['POST','GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Email has been sent', 'info')
        return redirect(url_for('users.signin'))
    return render_template('reset_request.html', title='Reset Password' , form=form)


@users.route('/reset_password/<token>', methods=['POST','GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Token is invalid or expired', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been changed. You can now log in','success')
        return redirect(url_for('users.signin'))
    return render_template('reset_token.html', title='Reset Password' , form=form)



# page 222

@users.route('/register',methods=['POST','GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('homee'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has now been created. You can now log in','success')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login',methods=['POST','GET'])
def  login():
    if current_user.is_authenticated:
        return redirect(url_for('homee'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('homee'))
        else:
            flash('Login unsuccesful, please check email or password ', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logoutt')
def logoutt():
    logout_user()
    return redirect(url_for('homee'))

quarantineradio/templates/account.html
{% extends "tutlayout.html" %}
{% block content %}

    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{image_file}}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
      <!-- <div class="content-section"> -->
        <form class="" action="" method="post" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb -4"> Account Info  </legend>
            <div class="form-group">
              {{ form.username.label(class="form-control-label") }}
              {% if form.username.errors %}
                {{ form.username(class=" form-control form-control-lg is-invalid ") }}
                <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                  <span> {{error}} </span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.username(class="form-control form-control-lg") }}
              {% endif %}
            </div>

            <div class="form-group">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid ") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span> {{error}} </span>
                  {% endfor %}
                </div>
              {% else %}
              {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.picture.label() }}
              {{ form.picture(class="form-control-file addimg")}}
              {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger"> {{error}} </span><br>
                {% endfor %}
              {% endif %}

            </div>

            <!-- {% for subfield in form.picture %}
              <tr>
                  <td>{{ subfield }}</td>
                  <img src="" alt="">
                  <td>{{ subfield.label }}</td>
              </tr>
              {% endfor %} -->
              <div class="pictures">
                <p>P1 IMG</p>
                <p>P1 IMG</p>
                <p>P1 IMG</p>
              </div>



          </fieldset>
          <div class="form-group">
            {{ form.submit(class="btn btn-outline-dark") }}
          </div>
        </form>
      <!-- </div> -->
    </div>
{% endblock content %}

quarantineradio/templates/account2.html
{% extends "tutlayout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{image_file}}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
      <!-- <div class="content-section"> -->
        <form class="" action="" method="post" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb -4"> Account Info  </legend>
            <div class="form-group">
              {{ form.username.label(class="form-control-label") }}
              {% if form.username.errors %}
                {{ form.username(class=" form-control form-control-lg is-invalid ") }}
                <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                  <span> {{error}} </span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.username(class="form-control form-control-lg") }}
              {% endif %}
            </div>

            <div class="form-group">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid ") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                  <span> {{error}} </span>
                  {% endfor %}
                </div>
              {% else %}
              {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.picture.label() }}
              {{ form.picture(class="form-control-file")}}
              {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger"> {{error}} </span><br>
                {% endfor %}
              {% endif %}

            </div>
          </fieldset>
          <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
      <!-- </div> -->
    </div>
{% endblock content %}

quarantineradio/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/main.css')}}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
    crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    {% if title %}
    <title> Quarantine Radio - {{title}}</title>
    {% else %}
    <title> Quarantine Radio </title>
    {% endif %}

  </head>
  <body>
    {% include 'includes/_message.html' %}
    {% block body %}{% endblock %}
    <script src="{{ url_for('static', filename= 'js/main.js')}}"></script>
    <!-- SocketIO-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
    <!-- custom SocketIO -->
    <script src="{{ url_for('static', filename= 'js/socketio.js')}}"></script>
    <script src="{{ url_for('static', filename= 'js/socketio2.js')}}"></script>
    <!-- custom chat js -->
    <script src="{{ url_for('static', filename= 'js/chat_page.js')}}"></script>
    <!-- Include the Web Playback SDK -->
    <script src="https://sdk.scdn.co/spotify-player.js"></script>

  </body>
</html>

quarantineradio/templates/create_room.html
{% extends "base.html" %}

<!-- {% block content %}

{% endblock content %} -->

{% block body %}
<body id="sign-in-page">
  <a href="{{ url_for('main.home') }}"> BACK TO ROOms PAGE</a>
<div class="l-form">
  <div class="shape1"></div>
  <div class="shape2"></div>
  <div class="create-form">
    <!-- <img class="form-img" src="{{ url_for('static', filename= 'img/login-img.svg')}}" alt=""> -->

    <form class="form-content" action="" method="POST">
      {{ form.hidden_tag() }}
      <h1 class="form-title"> {{ legend }} </h1>

      <div class="form-div form-div-signup">
        <div class="form-icon">
          <i class="far fa-envelope"></i>
        </div>
        <div class="form-div-input">
          {{ form.title.label(class="form-label") }}
          {% if form.title.errors %}
            {{ form.title(class="form-input is-invalid ") }}
            <div class="invalid-feedback">
              {% for error in form.title.errors %}
              <span> {{error}} </span>
              {% endfor %}
            </div>
          {% else %}
          {{ form.title(class="form-input") }}
          {% endif %}
        </div>

      </div>


      <div class="form-div form-div-signup">
        <div class="form-icon">
          <i class="fas fa-lock"></i>
        </div>
        <div class="form-div-input">
        {{ form.description.label(class="form-label") }}
        {% if form.description.errors %}
          {{ form.description(class="form-input is-invalid ") }}
          <div class="invalid-feedback">
            {% for error in form.description.errors %}
            <span> {{error}} </span>
            {% endfor %}
          </div>
        {% else %}
        {{ form.description(class="form-input") }}
        {% endif %}
      </div>
    </div>

    <div class="form-group">
      {{ form.submit(class="form-button") }}
    </div>
    </form>
  </div>

</div>
{% endblock body %}

quarantineradio/templates/home.html
{% extends 'base.html' %}

{% block body %}
<nav class="nav-container hide-mobile-active">
  <ul class="nav-links-2 ">
    <li class="logo"><img class="logo"src="{{ url_for('static', filename= 'img/b-logo.png')}}" alt="LOGO"></li>
    <li class="item"><a href="#"><i class="fas fa-home fa-2x navicon overlay-home"></i></a></li>
    <!-- <li class="item"><a href="#"><i class="fas fa-heart fa-2x navicon overlay-home"></i></a></li> -->
    <!-- <li class="item"><a href="#"><i class="fas fa-bell fa-2x navicon overlay-home"></i></a></li> -->
    <!-- <li class="item"><a href="#"><i class="fas fa-cog fa-2x navicon overlay-home"></i></a></li> -->
    <li class="item"><a href="{{ url_for('users.account') }}"><i class="fas fa-user fa-2x navicon overlay-home"></i></a></li>
    {% if current_user.is_authenticated%}
    <li class="item"><a href="{{ url_for('users.logout') }}"><i class="fa fa-sign-out fa-2x navicon overlay-home"></i></a></li>
    {% else %}
    {% endif %}

  </ul>
</nav>

<section class="top-bar show-mobile-active" >
  <div class="top-bar">
    <div class="menu" id="menu">
      <a href="#" onclick="openNav()"class="openBtn"><i class="fa fa-bars"></i> </a>

    </div>
  </div>
</section>

<section class="home-overlay show-mobile-active" id="nav">
  <a href="#" onclick="closeNav()"class="closeBtn">&times;</a>
  <div class="overlay-content">
    <div class="nav-img">
      <img class="nav-logo"src="{{ url_for('static', filename= 'img/b-logo.png')}}" alt="LOGO">
    </div>
    <div class="nav-user-profile">




          <img class="rounded-circle article-img-mobile" src="{{image_file}}" alt="">
          <p class="nav-name">{{ current_user.username }}</p>


    </div>
    <div class="nav-content">
      <a href="#"><i class="fas fa-user "></i> &nbsp;&nbsp;Home</a>
      <a href="{{ url_for('users.account') }}"><i class="fas fa-user "></i> &nbsp;&nbsp;Profile</a>
      <a href="{{ url_for('users.logout') }}"><i class="fas fa-home "></i> &nbsp;&nbsp;Logout</a>
    </div>
  </div>
</section>

<section class="home-showcase">
  <div class="home-showcase-content">
    <img class="logo-mobile show-mobile-active"src="{{ url_for('static', filename= 'img/b-logo.png')}}" alt="LOGO">
    <div class="home-search-box">
      <input class="input-box"type="text" placeholder="Search Room.." name="search">
      <a class="search-btn" href="#">
      <i class="fa fa-search "></i>
      </a>
    </div>
    <div class="global-local">
      <div class="global-local-mobile show-mobile-active ">
      <button class="room-button-home room-button-home-active remove-border-right" type="button" name="button">Global Room</button>
      <button class="room-button-home remove-border-left" type="button" name="button">Friends Room</button>
      </div>
      <div class="global-local-laptop hide-mobile-active">
        <a href="#">
          <i class="fas fa-user fa-2x global-icon-home"></i>
        </a>
        <a href="#">
          <i class="fas fa-globe fa-2x global-icon-home"></i>
        </a>
      </div>
    </div>

    <div class="rooms" id="home-rooms">
    {% for room in rooms.items %}
      <a href="{{ url_for('rooms.room',room_id=room.id)}}" class="btn btn-xl home-rooms m">
        <img class="rounded-circle article-img hide-mobile-active" src="{{ url_for('static', filename= 'img/' + room.room_creator.image_file) }}" alt="">
        <div class="room-info">
            <!-- <p class="select-room">{{room}} </p> -->
            <h1>{{room.title }}</h1>
            <p>By {{room.room_creator.username}} on {{room.date_posted.strftime('%Y-%m-%d')}}</p>
            <!-- <a href="{{url_for('users.user_rooms', username=room.room_creator.username)}}"> Click {{room.room_creator.username}}</a> -->
            <p>{{room.description}}</p>
        </div>
      </a>
      {% endfor%}

      <div class="page_num">

      {% for page_num in rooms.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if rooms .page == page_num %}
            <a class="pagination fill" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="pagination" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
      {% endfor%}
     </div>

      <a href="{{ url_for('rooms.post_new') }}" >
        <button class="home-btn"><i class="fa fa-plus"></i></button>
        <!-- <button class="home-btn" onclick="createRoom()"><i class="fa fa-plus"></i></button> -->
      </a>
    </div>
    <!-- <div class="home-buttons">
    </div> -->
  </div>
</section>

<!-- <section class="create-room-overlay" id="create-room-overlay">
  <div class="create-room-overlay-laptop">
    <div class="create-room-overlay-top">
      <p class="create-room-overlay-top-left" >Create Room</p>
      <div class="create-room-overlay-top-right">
        <a href="#"><i class="far fa-times-circle fa-2x close-room-Btn" onclick="createRoomClose()"></i></a>
        <a href="#"><i class="fas fa-check-circle fa-2x"></i></a>
      </div>
    </div>

    <input class="create-room-input" id="create-room-input" type="text" placeholder="Room Name">
    <input class="create-room-input" id="create-room-input" type="text"placeholder="Description">
    <input class="create-room-input" id="create-room-input" type="text" placeholder="Genre">
  </div>
</section> -->
{% endblock body %}

quarantineradio/templates/login.html
{% extends "tutlayout.html" %}
{% block content %}
  <div class="content-section">
    <form class="" action="" method="post">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb -4"> Log In</legend>

        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid ") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span> {{error}} </span>
              {% endfor %}
            </div>
          {% else %}
          {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>

        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid ") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
              <span> {{error}} </span>
              {% endfor %}
            </div>
          {% else %}
          {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class=" form-check ">
          {{ form.remember(class="form-check-input")}}
          {{ form.remember.label(class="form-check-label")}}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
        <small class="text-muted ml-2">
          <a href="{{ url_for('users.reset_request') }}">Fogot Password?</a>
        </small>
      </div>


    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need an account? <a class="ml-2" href="{{ url_for('users.register') }}"> Sign Up Now</a>
    </small>
  </div>
{% endblock content%}

quarantineradio/templates/signin.html
{% extends 'base.html' %}

{% block body %}
<body id="sign-in-page">
  <a href="{{ url_for('main.index') }}"> BACK TO HOME PAGE</a>
<div class="l-form">
  <div class="shape1"></div>
  <div class="shape2"></div>
  <div class="form">
    <img class="form-img" src="{{ url_for('static', filename= 'img/login-img.svg')}}" alt="">

    <form class="form-content" action="" method="POST">
      {{ form.hidden_tag() }}
      <h1 class="form-title"> Login </h1>
      <div class="form-div form-div-signup">
        <div class="form-icon">
          <i class="far fa-envelope"></i>
        </div>
        <div class="form-div-input">
          <!-- {{ form.email.label(class="form-label") }} -->
          {% if form.email.errors %}
            {{ form.email(class=" form-input is-invalid ") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
              <span class="padding-left"> {{error}} </span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-input") }}
          {% endif %}
        </div>
      </div>
      <div class="form-div form-div-signup">
        <div class="form-icon">
          <i class="fas fa-lock"></i>
        </div>
        <div class="form-div-input">
          <!-- {{ form.password.label(class="form-label") }} -->
          {% if form.password.errors %}
            {{ form.password(class=" form-input is-invalid ") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
              <span class="padding-left"> {{error}} </span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-input") }}
          {% endif %}
        </div>
      </div>
      <!-- <div class="">
        {{ form.remember(class="form-check-input")}}
        {{ form.remember.label(class="form-check-label")}}
      </div> -->

      <a class="create-account" href="{{ url_for('users.signup') }}"> Need an account? Sign up</a>
      {{ form.submit(class="form-button") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Fogot Passsword?</a>
      </small>
    </form>
  </div>

</div>
{% endblock body %}

quarantineradio/templates/user_rooms.html
{% extends 'tutlayout.html' %}

{% block content %}
<h1 class="mb-3"> Posts by {{user.username}} ({{posts.total}})</h1>

  {% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename= 'img/' + post.room_creator.image_file) }}" alt="">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2"  >{{ post.room_creator.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('rooms.room',room_id=post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.description }}</p>
      </div>
  </article>
  {% endfor%}
  {% for page_num in posts.iter_pages() %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_rooms', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% else %}
      <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_rooms', username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor%}
{% endblock content%}